name: app_turism
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_lints: ^4.0.0
  url_launcher: ^6.2.4
  adaptive_theme: ^3.6.0
  geolocator: ^10.0.0
  permission_handler: ^10.0.0
  sqflite: ^2.3.3+1
  path: ^1.8.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - lib/imagenes/
